export const operationParentModules: Record<string, string> = {
  activities: "dashboard",
  alerts: "dashboard",
  prospects: "crm",
  quotes: "billing",
  treasury: "finance",
  contracts: "legal",
  "business-plan": "legal",
  funding: "legal",
  compliance: "legal",
  formalities: "legal",
  recruitment: "hr",
  salaries: "hr",
  leave: "hr",
  expenses: "hr",
  time: "hr",
  tasks: "projects",
  gantt: "projects",
  collaboration: "projects",
  messaging: "projects",
  emailing: "marketing",
  sms: "marketing",
  advertising: "marketing",
  "content-generation": "ai",
  "financial-analysis": "finance",
  "document-generator": "documents",
  "data-chat": "ai",
  sav: "support",
  faq: "support",
  experts: "marketplace",
  trainers: "academy",
  consultants: "marketplace",
  resources: "academy",
  connections: "security",
  audit: "security",
  access: "security",
  permissions: "settings",
  users: "settings",
  roles: "settings"
};

export function getOperationParentModule(operationKey: string) {
  return operationParentModules[operationKey] ?? operationKey;
}
